### ISSUE TITLE
Read the docs?

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/cis_functions#8]
Hey @akatsoulas and @johngian I don't have read the docs access for Mozilla.  Can you set it up for this repo?

**Comment by johngian** [comment]
@andrewkrug we are using an account for our team specifically. I can grant you access.

**Comment by andrewkrug** [comment]
I have the access just need to set it up.

**Comment by johngian** [comment]
For more info:

* https://github.com/mozilla-iam/cis/tree/master/docs
* http://www.sphinx-doc.org/en/stable/tutorial.html

Let me know if you need further information.
